package fatfitandhealthy.dao;

// default package
// Generated 3 Jan, 2017 3:36:01 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "fatfitandhealthy")
public class Admin implements java.io.Serializable {

	private Integer id;
	private String email;
	private String password;
	private String firstname;
	private String lastname;
	private String image;
	private String role;
	private int permission;
	private String editTimestamp;
	private String createTimestamp;

	public Admin() {
	}

	public Admin(String email, String password, String firstname, String lastname, String image, String role,
			int permission, String editTimestamp, String createTimestamp) {
		this.email = email;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.image = image;
		this.role = role;
		this.permission = permission;
		this.editTimestamp = editTimestamp;
		this.createTimestamp = createTimestamp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "firstname", nullable = false)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "role", nullable = false)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "permission", nullable = false)
	public int getPermission() {
		return this.permission;
	}

	public void setPermission(int permission) {
		this.permission = permission;
	}

	@Column(name = "edit_timestamp", nullable = false)
	public String getEditTimestamp() {
		return this.editTimestamp;
	}

	public void setEditTimestamp(String editTimestamp) {
		this.editTimestamp = editTimestamp;
	}

	@Column(name = "create_timestamp", nullable = false)
	public String getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(String createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

}
