package fatfitandhealthy.dao;

// default package
// Generated 18 Dec, 2016 5:15:39 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Exercise generated by hbm2java
 */
@Entity
@Table(name = "exercise", catalog = "fatfitandhealthy")
public class Exercise implements java.io.Serializable {

	private Integer id;
	private String name;
	private float met;

	public Exercise() {
	}

	public Exercise(String name, float met) {
		this.name = name;
		this.met = met;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "met", nullable = false, precision = 12, scale = 0)
	public float getMet() {
		return this.met;
	}

	public void setMet(float met) {
		this.met = met;
	}

}
