package fatfitandhealthy.dao;

// default package
// Generated 21 Dec, 2016 4:53:43 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Exercise generated by hbm2java
 */
@Entity
@Table(name = "exercise", catalog = "fatfitandhealthy")
public class Exercise implements java.io.Serializable {

	private Integer id;
	private String name;
	private float met;
	private Set<ExerciseLog> exerciseLogs = new HashSet<ExerciseLog>(0);

	public Exercise() {
	}

	public Exercise(String name, float met) {
		this.name = name;
		this.met = met;
	}

	public Exercise(String name, float met, Set<ExerciseLog> exerciseLogs) {
		this.name = name;
		this.met = met;
		this.exerciseLogs = exerciseLogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "met", nullable = false, precision = 12, scale = 0)
	public float getMet() {
		return this.met;
	}

	public void setMet(float met) {
		this.met = met;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exercise")
	public Set<ExerciseLog> getExerciseLogs() {
		return this.exerciseLogs;
	}

	public void setExerciseLogs(Set<ExerciseLog> exerciseLogs) {
		this.exerciseLogs = exerciseLogs;
	}

}
