package fatfitandhealthy.dao;

// default package
// Generated 14 Dec, 2016 2:26:28 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FoodItems generated by hbm2java
 */
@Entity
@Table(name = "food_items", catalog = "fatfitandhealthy")
public class FoodItems implements java.io.Serializable {

	private Integer id;
	private String name;
	private String servingSize;
	private float cal;
	private float fat;
	private float cholesterol;
	private float sodium;
	private float potassium;
	private float carbs;
	private float fiber;
	private float sugars;
	private float protein;

	public FoodItems() {
	}

	public FoodItems(String name, String servingSize, float cal, float fat, float cholesterol, float sodium,
			float potassium, float carbs, float fiber, float sugars, float protein) {
		this.name = name;
		this.servingSize = servingSize;
		this.cal = cal;
		this.fat = fat;
		this.cholesterol = cholesterol;
		this.sodium = sodium;
		this.potassium = potassium;
		this.carbs = carbs;
		this.fiber = fiber;
		this.sugars = sugars;
		this.protein = protein;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "serving_size", nullable = false)
	public String getServingSize() {
		return this.servingSize;
	}

	public void setServingSize(String servingSize) {
		this.servingSize = servingSize;
	}

	@Column(name = "cal", nullable = false, precision = 12, scale = 0)
	public float getCal() {
		return this.cal;
	}

	public void setCal(float cal) {
		this.cal = cal;
	}

	@Column(name = "fat", nullable = false, precision = 12, scale = 0)
	public float getFat() {
		return this.fat;
	}

	public void setFat(float fat) {
		this.fat = fat;
	}

	@Column(name = "cholesterol", nullable = false, precision = 12, scale = 0)
	public float getCholesterol() {
		return this.cholesterol;
	}

	public void setCholesterol(float cholesterol) {
		this.cholesterol = cholesterol;
	}

	@Column(name = "sodium", nullable = false, precision = 12, scale = 0)
	public float getSodium() {
		return this.sodium;
	}

	public void setSodium(float sodium) {
		this.sodium = sodium;
	}

	@Column(name = "potassium", nullable = false, precision = 12, scale = 0)
	public float getPotassium() {
		return this.potassium;
	}

	public void setPotassium(float potassium) {
		this.potassium = potassium;
	}

	@Column(name = "carbs", nullable = false, precision = 12, scale = 0)
	public float getCarbs() {
		return this.carbs;
	}

	public void setCarbs(float carbs) {
		this.carbs = carbs;
	}

	@Column(name = "fiber", nullable = false, precision = 12, scale = 0)
	public float getFiber() {
		return this.fiber;
	}

	public void setFiber(float fiber) {
		this.fiber = fiber;
	}

	@Column(name = "sugars", nullable = false, precision = 12, scale = 0)
	public float getSugars() {
		return this.sugars;
	}

	public void setSugars(float sugars) {
		this.sugars = sugars;
	}

	@Column(name = "protein", nullable = false, precision = 12, scale = 0)
	public float getProtein() {
		return this.protein;
	}

	public void setProtein(float protein) {
		this.protein = protein;
	}

}
