package fatfitandhealthy.dao;

// default package
// Generated 3 Jan, 2017 3:36:01 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name = "post", catalog = "fatfitandhealthy")
public class Post implements java.io.Serializable {

	private Integer id;
	private int uid;
	private String ptext;
	private int likes;
	private String ctime;
	private String utime;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Like> likes_1 = new HashSet<Like>(0);

	public Post() {
	}

	public Post(int uid, String ptext, int likes, String ctime, String utime) {
		this.uid = uid;
		this.ptext = ptext;
		this.likes = likes;
		this.ctime = ctime;
		this.utime = utime;
	}

	public Post(int uid, String ptext, int likes, String ctime, String utime, Set<Comment> comments,
			Set<Like> likes_1) {
		this.uid = uid;
		this.ptext = ptext;
		this.likes = likes;
		this.ctime = ctime;
		this.utime = utime;
		this.comments = comments;
		this.likes_1 = likes_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "uid", nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	@Column(name = "ptext", nullable = false, length = 65535)
	public String getPtext() {
		return this.ptext;
	}

	public void setPtext(String ptext) {
		this.ptext = ptext;
	}

	@Column(name = "likes", nullable = false)
	public int getLikes() {
		return this.likes;
	}

	public void setLikes(int likes) {
		this.likes = likes;
	}

	@Column(name = "ctime", nullable = false)
	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

	@Column(name = "utime", nullable = false)
	public String getUtime() {
		return this.utime;
	}

	public void setUtime(String utime) {
		this.utime = utime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "post")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "post")
	public Set<Like> getLikes_1() {
		return this.likes_1;
	}

	public void setLikes_1(Set<Like> likes_1) {
		this.likes_1 = likes_1;
	}

}
