package fatfitandhealthy.dao;

// default package
// Generated 3 Jan, 2017 3:36:01 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * SystemLog generated by hbm2java
 */
@Entity
@Table(name = "system_log", catalog = "fatfitandhealthy")
public class SystemLog implements java.io.Serializable {

	private Integer id;
	private String timestamp;
	private int uid;
	private String message;
	private String ipaddress;

	public SystemLog() {
	}

	public SystemLog(int uid, String message, String ipaddress) {
		this.uid = uid;
		this.message = message;
		this.ipaddress = ipaddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	@Column(name = "timestamp", nullable = false)
	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "uid", nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	@Column(name = "message", nullable = false)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "ipaddress", nullable = false)
	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

}
