package fatfitandhealthy.dao;

// default package
// Generated 21 Dec, 2016 4:53:43 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserLogin generated by hbm2java
 */
@Entity
@Table(name = "user_login", catalog = "fatfitandhealthy")
public class UserLogin implements java.io.Serializable {

	private Integer id;
	private String email;
	private String password;
	private String status;
	private String image;
	private String editTimestamp;
	private String createTimestamp;

	public UserLogin() {
	}

	public UserLogin(String email, String password, String status, String image, String editTimestamp,
			String createTimestamp) {
		this.email = email;
		this.password = password;
		this.status = status;
		this.image = image;
		this.editTimestamp = editTimestamp;
		this.createTimestamp = createTimestamp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "edit_timestamp", nullable = false)
	public String getEditTimestamp() {
		return this.editTimestamp;
	}

	public void setEditTimestamp(String editTimestamp) {
		this.editTimestamp = editTimestamp;
	}

	@Column(name = "create_timestamp", nullable = false)
	public String getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(String createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

}
