package fatfitandhealthy.dao;

// default package
// Generated 19 Dec, 2016 5:55:57 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UsersPersonal generated by hbm2java
 */
@Entity
@Table(name = "users_personal", catalog = "fatfitandhealthy")
public class UsersPersonal implements java.io.Serializable {

	private int id;
	private String fname;
	private String lname;
	private String dob;
	private String mobNo;
	private String gender;

	public UsersPersonal() {
	}

	public UsersPersonal(int id, String fname, String lname, String dob, String mobNo, String gender) {
		this.id = id;
		this.fname = fname;
		this.lname = lname;
		this.dob = dob;
		this.mobNo = mobNo;
		this.gender = gender;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "fname", nullable = false)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "lname", nullable = false)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "dob", nullable = false)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "mob_no", nullable = false)
	public String getMobNo() {
		return this.mobNo;
	}

	public void setMobNo(String mobNo) {
		this.mobNo = mobNo;
	}

	@Column(name = "gender", nullable = false)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

}
